### ISSUE TITLE
Used implementations for baselines not included

### ISSUE THREAD

**Issue by floriandonhauser** [tmllab/Moderate-DS#1]
Dear authors,
I really enjoyed reading your paper and thank you for your contribution to the research area of data pruning / coreset selection.
It is very nice of you to publicly share the code for your developed approach. In the paper you compare it to existing approaches, the baselines.
I am unable to find these baselines in your repository but would like to reproduce the results.
Would you be willing to share the implementations you used for the baselines as well?

**Comment by Data-reindeer** [comment]
Dear authors,
I have the same question as **floriandonhauser** and look forward to seeing implementations of baselines.
