### ISSUE TITLE
implementation inconsistent with the paper

### ISSUE THREAD

**Issue by Isaachhh** [tmllab/Moderate-DS#2]
Dear authors,
In the paper, you define the center of one class by the **mean** of the representations,
![image](https://user-images.githubusercontent.com/93458689/234746550-e4f1b6da-ecce-4797-9298-17e3b602cf3c.png)
but in https://github.com/tmllab/Moderate-DS/blob/7f64d319624aab981dab1604a1aa3d528eb82f76/selection.py#L13 **median** is used.

May I ask the reason?
Thanks!

**Comment by xiaoboxia** [comment]
Sorry for the delayed reply. 

We find that it may be more stable when using the median in some cases. Therefore, in this repo, we use the median by default for users. You can still use the mean operation. The method still works.
