### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by Arpita2012** [tmllab/Moderate-DS#6]
Request to create requirements.txt. 

Even with latest version of torch, I am getting following error
 data_train = get_dataset(args, transform=train_transform, train=True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "2023_ICLR_Moderate-DS/utils.py", line 27, in get_dataset
    dataset = CIFAR100(root=args.data, train=train, transform=transform)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "2023_ICLR_Moderate-DS/datasets/dataset.py", line 65, in __init__
    super().__init__(root, transform=transform, target_transform=target_transform)
  File "2023_ICLR_Moderate-DS/datasets/vision.py", line 35, in __init__
    if isinstance(root, torch._six.string_classes):
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute '_six'

![image](https://github.com/tmllab/2023_ICLR_Moderate-DS/assets/30351816/47bfcf01-5f46-48c6-8905-e8dd50afde7e)

**Comment by ZaitianWang** [comment]
my github copilot suggests this is intended to provide compatibility for both python 2 and python 3, and might has been removed in python-3-only pytorch versions. so if using python 3 and latest pytorch, simply commenting the lines out would be fine.
